name: "EntrevistadorInteligente"
admins:
  - JamiltonQuintero
  - svg153
teams:
  - name: "admins"
    description: "Administrators of the organization"
    members:
      - JamiltonQuintero
      - JamiltonQuintero2 # la cuenta de backup del amigo Jamilton
      - svg153
  - name: "all"
    description: "All members of the organization"
    members:
      - JamiltonQuintero
      - svg153
      - Jorgeivan246
      - Rpeche-pk
      - gimore
      - DarkCodePE
      - ppsegura
      - Coshiloco
      - Kirenai
      - Lopez19
      - Mathi21as
      - danmondra
      - joaquincorimayo
default_branch_name: "main"
